<?php

/**
 * @file
 * Contains seminarios.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function seminarios_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the seminarios module.
    case 'help.page.seminarios':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Seminarios CCM') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme()
 * @return mixed
 */
function seminarios_theme() {
  $theme['seminarios_ccm'] = [
      'variables' => ['seminarios' => NULL],
      'template' => 'semana',
  ];

  return $theme;
}